"""Optional link between CobbAttack's lifetime and VoiceAttack's.

When settings["link_voiceattack"] is on, starting CobbAttack also starts
VoiceAttack (elevated, the way VAICOM needs it), and closing CobbAttack closes
VoiceAttack. Off (the default) they are fully independent — important for
people who launch everything from their own script in a fixed order.

The close half needs elevation (VoiceAttack runs as admin, so a plain taskkill
gets Access Denied). Rather than a second UAC prompt at quit time, we launch
one elevated PowerShell "janitor" at startup: it starts VoiceAttack if needed,
waits for our process to exit, then closes VoiceAttack gracefully. One admin
prompt total — the same one the old "Start with VoiceAttack" shortcut showed.

Before closing, the janitor re-reads settings.json: if the box was unticked
mid-session, it leaves VoiceAttack alone.
"""

import logging
import os
import subprocess
import threading

import config

log = logging.getLogger("cobb.valink")

VA_CANDIDATES = (
    r"C:\Program Files (x86)\VoiceAttack\VoiceAttack.exe",
    r"C:\Program Files\VoiceAttack\VoiceAttack.exe",
)

_JANITOR = """# generated by CobbAttack — do not edit (rewritten on every linked start)
$vaExe = '{va_exe}'
$settings = '{settings}'
if (-not (Get-Process VoiceAttack -ErrorAction SilentlyContinue)) {{
    Start-Process -FilePath $vaExe
}}
Wait-Process -Id {cobb_pid} -ErrorAction SilentlyContinue
try {{ $s = Get-Content $settings -Raw | ConvertFrom-Json }} catch {{ $s = $null }}
if ($s -ne $null -and -not $s.link_voiceattack) {{ exit }}
$va = Get-Process VoiceAttack -ErrorAction SilentlyContinue
if ($va) {{
    $null = $va.CloseMainWindow()
    if (-not $va.WaitForExit(8000)) {{
        Stop-Process -Id $va.Id -Force -ErrorAction SilentlyContinue
    }}
}}
"""

_started = False


def find_voiceattack():
    for path in VA_CANDIDATES:
        if os.path.exists(path):
            return path
    return None


def is_va_running():
    try:
        out = subprocess.run(
            ["tasklist", "/FI", "IMAGENAME eq VoiceAttack.exe"],
            capture_output=True, text=True,
            creationflags=subprocess.CREATE_NO_WINDOW).stdout
        return "VoiceAttack.exe" in out
    except OSError:
        return False


def start(app):
    """Start VoiceAttack (if needed) and arm close-on-exit. Idempotent."""
    global _started
    if _started:
        return
    va = find_voiceattack()
    if va is None:
        log.error("link on, but VoiceAttack.exe not found in Program Files")
        app.post("error", message="couldn't find VoiceAttack in Program Files — "
                                  "start it yourself, or install it there")
        return
    _started = True
    ps1 = os.path.join(config.ROOT, "va_link.ps1")
    with open(ps1, "w", encoding="utf-8") as f:
        f.write(_JANITOR.format(va_exe=va.replace("'", "''"),
                                settings=config.SETTINGS_PATH.replace("'", "''"),
                                cobb_pid=os.getpid()))
    was_running = is_va_running()
    # Elevate once: the janitor starts VoiceAttack (no prompt of its own, it is
    # already admin) and later closes it, which plain CobbAttack isn't allowed to do.
    subprocess.Popen(
        ["powershell", "-NoProfile", "-WindowStyle", "Hidden", "-Command",
         "Start-Process powershell -Verb RunAs -WindowStyle Hidden -ArgumentList "
         f"'-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File','\"{ps1}\"'"],
        creationflags=subprocess.CREATE_NO_WINDOW)
    if was_running:
        log.info("link: VoiceAttack already running — will close it when we quit")
        app.post("dropped", reason="link: VoiceAttack already running — it will close with me")
    else:
        log.info("link: starting VoiceAttack (admin prompt)")
        app.post("dropped", reason="link: starting VoiceAttack — say yes to the admin prompt")

        def check_started():
            if not is_va_running():
                app.post("error",
                         message="VoiceAttack didn't start — was the admin prompt refused? "
                                 "Untick the 🔗 box to run CobbAttack alone.")
        timer = threading.Timer(25.0, check_started)
        timer.daemon = True
        timer.start()
