"""Build commands.txt from a VAICOM VSPX keyword export (vaicom_keywords.txt).

The export is the raw "When I say" text of the AI Communications keyword
collection: top-level alternatives separated by ";", where an alternative may be
multipart — adjacent [a; b; c] groups whose spoken form is one pick per group.
A group with a trailing empty entry ("[WSO; Wizzo; ]") is optional.

commands.txt is the normalizer's firewall/snap list, so every line must be a
phrase VoiceAttack would actually accept. We expand the cartesian product of
each multipart alternative; if that explodes past PER_ALT_CAP we keep the
suffix-only renderings (valid whenever the prefix group is optional) and log it.
"""

import itertools
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "vaicom_keywords.txt")
DST = os.path.join(ROOT, "commands.txt")

PER_ALT_CAP = 20000


def split_top(text):
    """Split on ';' outside brackets."""
    parts, depth, cur = [], 0, []
    for ch in text:
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth = max(0, depth - 1)
        if ch == ";" and depth == 0:
            parts.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    parts.append("".join(cur))
    return [p.strip() for p in parts if p.strip()]


def expand(alt):
    """All spoken renderings of one alternative."""
    # tokens: bracket groups and literal runs, in order
    tokens = re.findall(r"\[[^\]]*\]|[^\[\]]+", alt)
    choices = []
    for tok in tokens:
        if tok.startswith("["):
            opts = [o.strip() for o in tok[1:-1].split(";")]
            if not any(o == "" for o in opts):
                opts = [o for o in opts if o]
            else:  # optional group: keep one empty pick
                opts = [o for o in opts if o] + [""]
            choices.append(opts)
        else:
            lit = tok.strip()
            choices.append([lit] if lit else [""])
    total = 1
    for c in choices:
        total *= len(c)
    if total > PER_ALT_CAP:
        # too big: keep only renderings where every optional group is skipped
        slimmed = []
        for c in choices:
            slimmed.append([""] if "" in c else c)
        print(f"capped ({total} combos), kept suffix-only: {alt[:60]}...")
        choices = slimmed
    out = []
    for combo in itertools.product(*choices):
        phrase = re.sub(r"\s+", " ", " ".join(combo)).strip()
        if phrase:
            out.append(phrase)
    return out


def main():
    if not os.path.exists(SRC):
        sys.exit(f"missing {SRC} — paste the VAICOM keyword export there first")
    with open(SRC, "r", encoding="utf-8-sig") as f:
        text = f.read().strip()
    phrases = set()
    recipients = set()
    for alt in split_top(text):
        # Non-final bracket groups are recipient prefixes (Tower, Two, Texaco…).
        # The cartesian expansion below CAPS huge alternatives to suffix-only, so
        # recipient+command combos are missing from commands.txt — the normalizer
        # re-assembles them at runtime from recipients.txt instead.
        groups = re.findall(r"\[([^\]]*)\]", alt)
        for g in groups[:-1] if groups else []:
            recipients.update(o.strip().lower() for o in g.split(";") if o.strip())
        for p in expand(alt):
            phrases.add(p.lower())
    with open(DST, "w", encoding="utf-8") as f:
        f.write("# generated by tools/make_commands.py from vaicom_keywords.txt\n")
        for p in sorted(phrases):
            f.write(p + "\n")
    rec_dst = os.path.join(ROOT, "recipients.txt")
    with open(rec_dst, "w", encoding="utf-8") as f:
        f.write("# generated by tools/make_commands.py — recipient/callsign prefixes\n")
        for r in sorted(recipients):
            f.write(r + "\n")
    print(f"{len(phrases)} phrases -> {DST}")
    print(f"{len(recipients)} recipients -> {rec_dst}")


if __name__ == "__main__":
    main()
